server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.99.209.31:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC 
    username: root 
    password: a452118234 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml 
  # 扫描pojo类的位置,在此处指明扫描实体类的包，在mapper中就可以不用写pojo类的全路径名了 
  type-aliases-package: com.zhoulianchang.mybatis.entity
  # mybatis会将sql语句打印到控制台 方便测试 
  # configuration: 
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
